---
title: pocketworks
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  meta-available-jobs:
    title: meta-available-jobs
    output: false
  meta-post-type:
    title: meta-post-type
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    description: ''
    image: ''
    tagline: 
    client: 
    client-article: 
    grid-title: 
    case-study-challenge: 
    case-study-outcome: 
    hero-image: 
    meta-post-type: 
- scope:
    path: ''
    type: meta-available-jobs
  values:
    more-info-link: ''
    more-info-link-text: ''
site_url: http://www.pocketworks.co.uk/
version: 1.0
excerpt_separator: "<!--more-->"
baseurl: ''
permalink: "/blog/:year-:month-:day-:title/"
sass:
  sass_dir: _sass
  style: compressed
include:
- _pages
exclude:
- ".gitignore"
- README.md
- Gemfile
- Gemfile.lock
- scripts
markdown: kramdown
kramdown:
  auto_ids: true
  auto_id_stripping: true
gems:
- jekyll-feed
compress_html:
  clippings: []
  blanklines: false
  profile: false
