---
title: pocketworks
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  meta-clients:
    title: meta-clients
    output: false
  meta-job-role-details:
    title: meta-job-role-details
    output: true
  meta-our-skills:
    title: meta-our-skills
    output: false
  meta-our-values:
    title: meta-our-values
    output: false
  meta-post-type:
    title: meta-post-type
    output: false
  meta-product-applications:
    title: meta-product-applications
    output: false
  meta-product-steps:
    title: meta-product-steps
    output: false
  meta-sectors:
    title: meta-sectors
    output: false
  meta-team-members:
    title: meta-team-members
    output: false
  meta-technology-expertise:
    title: meta-technology-expertise
    output: false
  meta-what-we-do:
    title: meta-what-we-do
    output: false
  meta-why-work-with-us:
    title: meta-why-work-with-us
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    description: ''
    image: ''
    tagline: 
    client: 
    client-article: 
    grid-title: 
    case-study-challenge: 
    case-study-outcome: 
    hero-image: 
    meta-post-type: 
- scope:
    path: ''
    type: meta-clients
  values:
    image: ''
- scope:
    path: ''
    type: meta-job-role-details
  values:
    more-info-link: ''
    more-info-link-text: ''
- scope:
    path: ''
    type: meta-our-skills
  values:
    image: ''
- scope:
    path: ''
    type: meta-product-applications
  values:
    application-type: ''
- scope:
    path: ''
    type: meta-product-steps
  values:
    step-type: ''
    image: ''
- scope:
    path: ''
    type: meta-sectors
  values:
    image: ''
- scope:
    path: ''
    type: meta-team-members
  values:
    image: ''
    job-title: ''
    email: ''
    is-executive: false
    linkedin-profile: ''
- scope:
    path: ''
    type: meta-technology-expertise
  values:
    is-tech-expertise: false
url: http://www.pocketworks.co.uk
site_url: http://www.pocketworks.co.uk/
version: 1.0
excerpt_separator: "<!--more-->"
baseurl: ''
permalink: "/blog/:year-:month-:day-:title/"
sass:
  sass_dir: _sass
  style: compressed
include:
- _pages
exclude:
- ".gitignore"
- README.md
- Gemfile
- Gemfile.lock
- scripts
- _redirects
markdown: kramdown
kramdown:
  auto_ids: true
  auto_id_stripping: true
gems:
- jekyll-sitemap
compress_html:
  clippings: []
  blanklines: false
  profile: false
