---
title: pocketworks
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    type:
    - Blog
    - Case Study
    - Product
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    date: ''
    description: ''
    image: ''
site_url: http://www.pocketworks.co.uk/
version: 1.0
excerpt_separator: "<!--more-->"
baseurl: ''
permalink: "/blog/:year-:month-:day-:title/"
sass:
  sass_dir: _sass
  style: compressed
include:
- _pages
exclude:
- ".gitignore"
- README.md
- Gemfile
- Gemfile.lock
- scripts
markdown: kramdown
kramdown:
  auto_ids: true
  auto_id_stripping: true
gems:
- jekyll-feed
compress_html:
  clippings: []
  blanklines: false
  profile: false
