language: ruby
rvm:
  - 2.3
before_script:
  # Markdown Linter using custom rule style file.
  #- mdl README.md _posts _pages --style _linter/markdown-linter-style.rb
  # Github Pages needs the baseurl field to be "m-lab.github.io" to render properly in forked
  # repos, but when we deploy to production, we need the baseurl field to be empty. This
  # command replaces "m-lab.github.io" with an empty string.
  #- sed -ie '/^baseurl/s/\/m-lab\.github\.io//' _config.yml
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --file-ignore "/mlab_observatory/","/ndt/"
branches:
  only:
  - master
  - gh-pages
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
deploy:
  - chmod +x ./scripts/deploy.sh
  - ./scripts/deploy.sh
