---
ipad:
  forms:
    intro:
    - header: PocketFORMS iPad App
      desc: Create forms on the iPad in seconds with no technical knowledge. Perfect
        for customer data capture, field surveys, exhibition stands and in retail
        environments.
    - header: Get early access
      desc: Get notified when we launch (we'll not share your details)
    fields:
    - name: name
      type: text
      placeholder: 'Your Name e.g: Mark Smith'
      validation-rule: maxlen:4
      validation-msg: Please enter at least 4 chars
    - name: email
      type: email
      placeholder: 'Your Email e.g: mark@ibm.com'
      validation-rule: email
      validation-msg: Please enter a valid email
    - name: subject
      type: text
      placeholder: 'Job Role e.g: Marketing Director'
      validation-rule: maxlen:4
      validation-msg: Please enter a role
    - name: devices
      type: text
      placeholder: 'I want it for? e.g: iPad, iPhone, Android Tablet'
      validation-rule: maxlen:4
      validation-msg: Please enter at least 4 chars
    - name: message
      type: textarea
      placeholder: What would you ideally use PocketFORMS for? Any specific needs?
      validation-rule: required
      validation-msg: What would you ideally use PocketFORMS for? Any specific needs?
    btn-text: Get early access when we launch
  applications:
    id: applications
    header: For many business activities
    rows:
    - row:
      - app:
          header: Exhibition Lead Capture
          desc: Create and publish forms so you can capture information about visitors
            to your stand during an exhibition or event.
      - app:
          header: Self Service Customer Kiosk
          desc: Give customers a self-service kiosk where they can complete a fast
            survey and leave their opinions or contact details.
    - row:
      - app:
          header: Retail Shop Floor &amp; Showroom
          desc: Staff use a form to collect information from customers on the shop
            floor, and send that data to others in their team.
      - app:
          header: Field Sales
          desc: Sales reps can use PocketFORMS to capture information during meetings.
            That data is automatically sent back to base for analysis.
    - row:
      - app:
          header: On-Site Surveys
          desc: Surveyors and technical sales can record information about a project
      - app:
          header: Work Orders
          desc: For field service companies. Capture cusotmer information, perform
            an inspection, and fill out information about a job.
  applications-forms:
    id: application-forms
    header: Simple effective forms for the iPad
    desc: pocketFORMS helps companies gather data from their staff working in the
      field.
    rows:
    - row:
      - app:
          header: Work without paper
          desc: Your staff can use the iPad even if they have no 4G or WiFi connection.
            The data they enter will be available to you as soon as a connection is
            available.
      - app:
          header: Works offline
          desc: Your staff can use the iPad even if they have no 4G or WiFi connection.
            The data they enter will be available to you as soon as a connection is
            available.
    - row:
      - app:
          header: Reduce costs
          desc: Reduce costs by eliminating double entry of data where paper forms
            are typed up. Your forms can include drop down lists and auto-complete.
      - app:
          header: Increase accuracy
          desc: Increase the accuracy of data with multiple choice questions, this
            reduces spelling mistakes and makes it easier for your to analyse data.
    - row:
      - app:
          header: Work with your data
          desc: Automatically import data into Excel, your web site, or your database
            systems.
      - app:
          header: Security
          desc: Use in-built security allowing safe capture of sensitive data.
  steps:
    id: howitworks
    items:
    - text: Quickly create a new iPad form, based on a PDF or Word Document you already
        use. It only takes a few minutes.
      img: "/images/pocketmedia/icon-orange-pdf.png"
    - text: Ask your team to install the iPad app. Within seconds they can see your
        forms and complete them at any time.
      img: "/images/pocketmedia/icon-orange-girl-ipad.png"
    - text: Get notified when forms are completed, and use the control panel to download
        data as a spreadsheet.
      img: "/images/pocketmedia/ipad-orange-charts.png"
    - text: Add more forms, or tweak them forms to make them fit your business perfectly.
        Staff use the same app to access all your forms.
      img: "/images/pocketmedia/ipad-orange-builder.png"
  quote:
    img: "/images/about/th.png"
    alt: Picture of Tobin
    text: Most companies we meet want to take small steps when it comes to using the
      iPad to streamline their business. When it comes to data collection, they just
      need an easy way to collect and analyse data without wasting time and money
      on manual work. pocketFORMS helps with this. We give companies simple and low
      cost tools to collect and analyze data from field workers using iPads.
    author: Tobin Harris, Director, Pocketworks
  solutions:
    header: Our iPad forms solutions are ideal for
    btn-text: Interested? Contact us for more information
    btn-url: "/contact/"
    items:
    - Healthcare companies with agents collecting data at customer site
    - Manufacturing companies with complex quoting requirements
    - Capturing customer data at exhibitions and conferences
    - Perfect for sales reports, expenses, surveys, conference feedback, product returns
      and more.
pocketmedia:
  features:
    id: features
    header: A modern, efficient way to sell
    desc: PocketMEDIA is a solution allowing companies to quickly adopt modern mobile
      technology in their sales activities.
    rows:
    - row:
      - app:
          header: Customised to your business
          desc: Every company is different. PocketMEDIA is designed to be customised
            for your business, so we can adapt the way it looks, the branding, and
            how information is structured.
      - app:
          header: Share everything
          desc: PocketMEDIA gives you a simple way of distributing your sales materials
            to your sales team using iPads; Videos, PDFs, Word files, Powerpoint files,
            images, or even entire web sites.
    - row:
      - app:
          header: Always up to date
          desc: Increased legal compliance, and reduced cost of distributing brochures.
            PocketMEDIA fetches sales materials from the cloud, so your sales team
            always have the latest and greatest content.
      - app:
          header: Close the loop
          desc: See how reps are using the sales materials with customers, and feed
            that information into your marketing content strategy. PocketMEDIA collects
            analytics showing the different materials each rep is using, and for how
            long with each customer.
    - row:
      - app:
          header: Interactive Presentations
          desc: Present interactive presentations which include audio, video, cost
            calculators or animations.
      - app:
          header: Customer Leave Pieces
          desc: Reps can elect to send leave pieces to customers during their meeting,
            even if there is no internet connection.
    - row:
      - app:
          header: Capture call notes
          desc: PocketMEDIA keeps a list of customers and calls, giving reps a simple
            way to capture call notes before, during or after the meeting.
      - app:
          header: Integrate with anything
          desc: Integration with CRMs, reward platforms or ERP is possible. SalesForce,
            SugarCRM, Microsoft Dynamics, or any other CRM you might use.
    final-btn:
      btn-text: Get your free trial, and start selling more effectively
      btn-url: "/demo_sign_up/"
    final-link:
      link-text: How PocketMEDIA could benefit your business
      link-url: "/ipad-sales-apps/"
  example:
    header: Example of how you could use PocketMEDIA
    id: howitworks
    items:
    - text: Your marketing team upload PDF sales aids, videos and other materials
        to a simple website
      img: "/images/pocketmedia/icon-orange-pdf.png"
    - text: Sales reps access materials via the iPad app and use them in face to face
        meetings
      img: "/images/pocketmedia/icon-orange-girl-ipad.png"
    - text: Marketing use the analytics to track how the team are using materials
      img: "/images/pocketmedia/ipad-orange-charts.png"
    - text: Marketing use that knowledge to improve materials and manage their usage
      img: "/images/pocketmedia/ipad-orange-builder.png"
  process:
    header: What's the process?
    id: process
    items:
    - text: Tell us what you're looking to achieve. We can come to your office to
        work on ideas and possible solutions.
      img: "/images/pocketmedia/icon-meeting.png"
    - text: We'll devise  a solution to get you up and running quickly. A great first
        step toward your long term objectives
      img: "/images/pocketmedia/icon-solution.png"
    - text: Our technical team deliver the first phase of a bespoke solution that
        fits your needs, often within weeks or a few months.
      img: "/images/pocketmedia/icon-builders.png"
    - text: Phase one is done! Marketing and sales teams start using their new digital
        sales solution. Back to step one to plan the next phase...
      img: "/images/pocketmedia/icon-woman-ipad.png"
  quote:
    img: "/images/about/th.png"
    alt: Picture of Tobin
    text: For over four years, we've been helping companies use iPads as a tool for
      supporting face to face sales. We've learnt that each company is different;
      they adapt their sales to their own offering and market position. Because of
      this, PocketMEDIA is designed to be adapted to each company, allowing teams
      to sell in the most effective way possible.
    author: Tobin Harris, Director, Pocketworks
  coming-soon:
    img: "/images/pocketmedia/pocketmedia-sales-trip-optimiserthumb.png"
    header: Coming Soon! Remove dead travel time
    desc: Reduce dead travel time using the sales trip planner. View your upcoming
      appointments on a map, select convenient contacts and create tentative appointments.
    link-text: Learn More
    link-url: /pocketmedia/sales-travel-mapper/
  choice:
    img: "/images/pocketmedia/pocketmedia-call-list.png"
    header: From CRM to ERP. Your choice.
    tagline: PocketMEDIA can be configured in any way you need, so if you want your
      customer, product or financial data in there, we can do it.
    desc: PocketMEDIA can be integrated with many systems to pull information from
      your different systems together. Including CRMs, single sign-on servers such
      as ActiveDirectory, or your performance management system.
  pricing:
    id: costs
    header: PocketMEDIA Pricing
    header-desc-items:
    - We aim to give companies a simple, low cost way of distributing materials to
      workers in the field. We also have more sophisticated installation options if
      you need them.
    - These costs should help you get an idea, but the best thing to do is perform
      a trial speak and speak to us; we can tweak it based on your needs and how much
      support and customisation you need.
    columns:
    - header: Simple
      btn-text: Get your free trial <br/>and start selling more effectively
      btn-link: "/demo_sign_up/"
      btn-class: btn-cta
      paras:
      - para:
        - "<b>£1,500 setup fee</b>"
        - "<b>£6 per user per month</b>"
        - "<i>Discounts available for over 2000 users</i>"
      - para:
        - Branded to your business
        - Have your own iPad app name and icon
        - Any number of reps; from 1 to 10,000
        - We'll setup your staff and users
        - UK 9am-5pm email and telephone support
        - Consultancy and advice via telephone
        - Training via telephone (onsite available)
        - Save time, we'll upload materials for you
    - header: Sophisticated
      btn-text: Get your free trial <br/>and start selling more effectively
      btn-link: "/demo_sign_up/"
      btn-class: btn-cta
      paras:
      - para:
        - "<b>£5,000 setup fee</b>"
        - "<b>£10 per user per month</b>"
        - "<i>Discounts available for over 2000 users</i>"
      - para:
        - ActiveDirectory integration
        - Custom reports
        - Face to face workshops and advice
        - Quarterly performance reviews and meeting attendance
        - ''
        - Branded to your business
        - Have your own iPad app name and icon
        - Any number of reps;  from 1 to 10,000
        - We'll setup your staff and users
        - UK 9am-5pm email and telephone support
        - Training via telephone (onsite available)
        - Save time, we'll upload materials for you
    - header: Tailored
      btn-text: Contact us for more info
      btn-link: "/contact/"
      btn-class: btn-primary
      paras:
      - para:
        - "<b>£15,000+</b>"
        - "<b>£5-£10 per user per month</b>"
      - para:
        - ''
        - "<i>Sometimes you need something that adapts perfectly to your business.
          The tailored option means we come and see you, then make it all work just
          how you need it.</i>"
      - para:
        - Tell us what features you need
        - We can integrate with CRM or ERP
        - Host on your own servers or ours
        - Face to face workshops and advice
---

